### ISSUE TITLE
Creating profiles based on predefined preferences

### ISSUE THREAD

**Issue by risufaj** [francois-durand/svvamp#5]
Hello,

I am looking to create profiles based on some predefined global preferences. For instance, let's say that there are 5 candidates with these global preferences `[0.03, 0.24, 0.33, 0.24, 0.16]` and I would like to generate 10k voters based on these preferences. Is there a way to achieve this using svvamp?

Thanks in advance!

**Comment by francois-durand** [comment]
Do you mean that you want all voters to share the same preferences, for
example to think that the first candidate has utility 0.03, the second
0.24, and so on?

Le lun. 6 mars 2023 à 16:51, Ralvi Isufaj ***@***.***> a
écrit :

**Comment by risufaj** [comment]
hey and thanks for the reply. I mean the latter, that the first candidate has utility 0.03 and so on.

**Comment by francois-durand** [comment]
Ok, so the matrix of utilities (where rows = voters and columns =
candidates) would be:
[
    [0.03, 0.24, 0.33, 0.24, 0.16],
    ...
    [0.03, 0.24, 0.33, 0.24, 0.16]
]

Is that correct?

Le mar. 7 mars 2023 à 10:04, Ralvi Isufaj ***@***.***> a
écrit :

**Comment by risufaj** [comment]
ah no, then I didn't express myself correctly. Apologies, as this is not my field of expertise. What I am trying to achieve, is to create user preferences in such a way that candidate 1 is the most preferred for 3% of the voters, candidate 2 is the most preferred for 24% of the users and so on. I assume to achieve a complete or even partial ordering one would need information also about what percentage of users have a candidate as their second favorite and so on. Does that make sense?

**Comment by francois-durand** [comment]
You can do:

profile = Profile(preferences_ut=[[1, 0, 0, 0, 0]] * 30 + [[0, 1, 0, 0, 0]]
* 240 + ...)

This way, 30 voters will prefer candidate 1 and be indifferent between
candidates 2, 3, 4, and 5; 240 voters will prefer candidate 2 and be
indifferent between the others; etc. Of course, you can (and probably
should) adapt this example so that voters have preferences beyond their top
candidate.

Le mar. 7 mars 2023 à 10:16, Ralvi Isufaj ***@***.***> a
écrit :

**Comment by risufaj** [comment]
makes sense, thanks a lot for your effort!
